FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV RETRIEVER_SERVICE_URL http://flask-retrieval:8084
ENV INFERENCE_SERVICE_URL http://ollama:11434/api/generate
ENV MODEL_NAME granite3.2:latest

# Create working directory
WORKDIR /app

# Copy application code
COPY main.py ./main.py

COPY ./images_BWI_Docs_V1_4142bff4928f13415914eedf6627ca39 ./

# Install Python dependencies
RUN pip install --upgrade pip && pip install \
    flask \
    requests

# Expose server port
EXPOSE 8001

# Start the Flask app
CMD ["python", "main.py"]
